/* eslint-disable max-len */
export default [
  {
    answer:
      "<p>Vous ne pouvez pas bénéficier d’un remboursement par l’Assurance Maladie en cas d’accès direct au psychologue.</p><p>Pour bénéficier d’une prise en charge par l’Assurance Maladie de séances chez le psychologue pour vous ou votre enfant, vous devez consulter votre médecin traitant ou, le cas échéant, un médecin impliqué dans votre prise en charge. Ce médecin peut être par exemple, votre médecin traitant, un médecin en ville (généraliste, pédiatre, gériatre…), un médecin scolaire, un médecin des services de santé universitaires, un médecin hospitalier. </p><p>L’implication du médecin à l’entrée du dispositif est indispensable, car elle vous permet d’être orienté(e) vers la prise en charge la plus adaptée à votre situation. Le médecin vérifie notamment l’absence de signes d’alerte ou de risque suicidaire. </p><p>En cas de besoin, votre médecin vous oriente vers un psychologue participant au dispositif, en vous remettant un « courrier d’adressage ». </p><p> Vous pouvez consulter la liste des psychologues partenaires <a href='/annuaire' rel='nofollow noopener'> ici</a>. Elle est régulièrement actualisée en fonction de l’entrée dans le dispositif de nouveaux psychologues.</p>",
    question:
      "Que faire si je souhaite voir un psychologue ? Puis-je prendre rendez-vous directement chez le psychologue ?",
  },
  {
    answer:
      "<p>Votre médecin vous a orienté vers le dispositif « Mon soutien psy », en vous remettant un « courrier d’adressage ».</p><p>Vous pouvez alors prendre rendez-vous chez un psychologue conventionné de votre choix parmi les psychologues partenaires du dispositif, y compris un psychologue exerçant hors de votre département de résidence. La liste, régulièrement actualisée avec l’adhésion de nouveaux psychologues, est disponible ici (à venir).</p><p>Les psychologues recensés dans cet annuaire sont volontaires pour participer au dispositif et ont signé une convention avec l’Assurance Maladie. Dans l’annuaire, vous trouverez leurs coordonnées, leurs lieux d’exercice ainsi que leurs souhaits s’agissant du public pris en charge (adultes uniquement, enfants/adolescents uniquement, ou adultes <b>et</b> enfants/adolescents). </p><p>Les psychologues indiquent aussi s’ils acceptent de réaliser des séances à distance. A noter, seule la première séance, l’entretien d’évaluation, est obligatoirement en présentiel.</p><p>Les psychologues partenaires ont été sélectionnés sur la base de critères de formation et d’expérience permettant d’assurer la qualité de la prise en charge proposée. Ces psychologues peuvent exercer en libéral ou en exercice salarié dans un centre de santé ou une maison de santé pluri-professionnelle.</p><p>Dans le cadre du dispositif, seules les séances réalisées, sur orientation d’un médecin, par les psychologues listés <a href='/annuaire' rel='nofollow noopener'> ici </a> sont remboursées. </p>",
    question:
      "Après avoir consulté mon médecin, puis-je prendre rendez-vous chez le psychologue de mon choix ?",
  },
];
